"""GUI theme definitions for SubjectDraw."""

DEFAULT_GUI_THEME = "浅色极简"

THEMES = {
    "浅色极简": {
        "sidebar_bg": "#1E1E2E",
        "sidebar_fg": "#CDD6F4",
        "sidebar_active": "#313244",
        "sidebar_accent": "#89B4FA",
        "bg": "#F0F2F5",
        "card": "#FFFFFF",
        "primary": "#5B7FFF",
        "primary_h": "#4A6EE0",
        "accent": "#7C8CF8",
        "border": "#E0E3E8",
        "text": "#1A1A2E",
        "text2": "#4A4A6A",
        "muted": "#8E8EA0",
        "input_bg": "#FAFBFC",
        "success": "#2E8B57",
        "error": "#C0392B",
        "btn_primary_bg": "#5B7FFF",
        "btn_primary_fg": "#FFFFFF",
        "btn_secondary_bg": "#E8EBF0",
        "btn_secondary_fg": "#4A4A6A",
        "scrollbar_bg": "#E0E3E8",
        "scrollbar_fg": "#B0B3B8",
        "link": "#5B7FFF",
        "hover_bg": "#F0F2F5",
        "sidebar_width": 180,
        "card_radius": 8,
        "font_family": "Microsoft YaHei UI",
        "font_size": 10,
    },
    "深邃暗色": {
        "sidebar_bg": "#11111B",
        "sidebar_fg": "#CDD6F4",
        "sidebar_active": "#1E1E2E",
        "sidebar_accent": "#89B4FA",
        "bg": "#1E1E2E",
        "card": "#313244",
        "primary": "#89B4FA",
        "primary_h": "#74C7EC",
        "accent": "#F5C2E7",
        "border": "#45475A",
        "text": "#CDD6F4",
        "text2": "#A6ADC8",
        "muted": "#6C7086",
        "input_bg": "#45475A",
        "success": "#A6E3A1",
        "error": "#F38BA8",
        "btn_primary_bg": "#89B4FA",
        "btn_primary_fg": "#1E1E2E",
        "btn_secondary_bg": "#45475A",
        "btn_secondary_fg": "#CDD6F4",
        "scrollbar_bg": "#45475A",
        "scrollbar_fg": "#585B70",
        "link": "#89B4FA",
        "hover_bg": "#313244",
        "sidebar_width": 180,
        "card_radius": 8,
        "font_family": "Microsoft YaHei UI",
        "font_size": 10,
    },
    "暖阳米白": {
        "sidebar_bg": "#3D2B1F",
        "sidebar_fg": "#F5E6D3",
        "sidebar_active": "#5C3D2E",
        "sidebar_accent": "#E8A87C",
        "bg": "#FAF3EB",
        "card": "#FFFFFF",
        "primary": "#D4845E",
        "primary_h": "#C0704A",
        "accent": "#E8A87C",
        "border": "#E8DDD0",
        "text": "#3D2B1F",
        "text2": "#6B5344",
        "muted": "#9C8B7E",
        "input_bg": "#FDF8F3",
        "success": "#6B8E5A",
        "error": "#C0392B",
        "btn_primary_bg": "#D4845E",
        "btn_primary_fg": "#FFFFFF",
        "btn_secondary_bg": "#F0E6DA",
        "btn_secondary_fg": "#6B5344",
        "scrollbar_bg": "#E8DDD0",
        "scrollbar_fg": "#C8B8A8",
        "link": "#D4845E",
        "hover_bg": "#F5EDE4",
        "sidebar_width": 180,
        "card_radius": 8,
        "font_family": "Microsoft YaHei UI",
        "font_size": 10,
    },
    "莫兰迪灰": {
        "sidebar_bg": "#2C3038",
        "sidebar_fg": "#D4D4D8",
        "sidebar_active": "#3A3E46",
        "sidebar_accent": "#B8A9C9",
        "bg": "#E8E8E4",
        "card": "#F5F5F0",
        "primary": "#8B7E9A",
        "primary_h": "#7A6D89",
        "accent": "#B8A9C9",
        "border": "#D4D4D0",
        "text": "#2C3038",
        "text2": "#5A5E66",
        "muted": "#8E8E94",
        "input_bg": "#FAFAF5",
        "success": "#7A9E7E",
        "error": "#C47070",
        "btn_primary_bg": "#8B7E9A",
        "btn_primary_fg": "#FFFFFF",
        "btn_secondary_bg": "#E4E4E0",
        "btn_secondary_fg": "#5A5E66",
        "scrollbar_bg": "#D4D4D0",
        "scrollbar_fg": "#B0B0B0",
        "link": "#8B7E9A",
        "hover_bg": "#EDEDEA",
        "sidebar_width": 180,
        "card_radius": 8,
        "font_family": "Microsoft YaHei UI",
        "font_size": 10,
    },
}


def list_gui_themes():
    return list(THEMES.keys())
